### ISSUE TITLE
Interested in contributing 

### ISSUE THREAD

**Issue by simontorres** [astropy/astropy-sphinx-theme#3]
I've been playing with modifications to other templates but always attached to a project. Is there a way to visualize the template without having to build the documentation of a project? Not really familiar with this kind of development.

Some "where-to-look" kind of help should suffice.

**Comment by astrofrog** [comment]
@simontorres - I'm not aware of an easy way without building documentation, but you could set up a minimal set of documentation with Sphinx that would build very fast to get a preview of the theme. I'll find out if there are easier ways and will update the README.

**Comment by simontorres** [comment]
Thanks!, Then I will experiment with a basic project.
