### ISSUE TITLE
Dropdown menu for About should show links arranged vertically

### ISSUE THREAD

**Issue by astrofrog** [astropy/astropy-sphinx-theme#7]
The **About** menu added in #4 looks a little different to the one for the main website:

**This theme**

<img width="579" alt="Screenshot 2019-04-24 at 14 01 48" src="https://user-images.githubusercontent.com/314716/56661399-90fc6400-6699-11e9-8bff-8432cc014f12.png">

**Main astropy.org website**

<img width="293" alt="Screenshot 2019-04-24 at 14 01 55" src="https://user-images.githubusercontent.com/314716/56661393-8e9a0a00-6699-11e9-9476-6380a555312a.png">

@kakirastern - is there any way to make the one here resemble the website one more?

**Comment by kakirastern** [comment]
Yup, I will work on it soon so that the two match.

**Comment by kakirastern** [comment]
The rendering is different from the one I got too, since the one I had was centered, and not to the side. Let me find out what's wrong...
